#!/bin/bash
cp unknow.svg sth-6-2.svg
cp unknow.svg sth-6-3.svg
cp unknow.svg sth-6-4.svg
cp unknow.svg sth-6-5.svg
cp unknow.svg sth-6-6.svg
cp unknow.svg sth-6-7.svg
cp unknow.svg sth-6-8.svg
cp unknow.svg sth-6-9.svg
cp unknow.svg sth-6-10.svg
cp unknow.svg sth-6-11.svg
cp unknow.svg sth-6-12.svg
cp unknow.svg sth-6-13.svg
cp unknow.svg sth-6-14.svg
cp unknow.svg sth-6-15.svg
cp unknow.svg sth-6-16.svg
cp unknow.svg sth-6-17.svg
cp unknow.svg sth-6-18.svg
cp unknow.svg sth-6-19.svg
cp unknow.svg sth-6-20.svg
cp unknow.svg sth-6-21.svg
cp unknow.svg sth-6-22.svg
cp unknow.svg sth-6-23.svg
cp unknow.svg sth-6-24.svg
cp unknow.svg sth-6-25.svg
cp unknow.svg sth-6-26.svg
cp unknow.svg sth-6-27.svg
cp unknow.svg sth-6-28.svg
cp unknow.svg sth-6-29.svg

